kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: image-server
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - image-server
        from:
          kind: ImageStreamTag
          name: image-server:latest
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: image-server
    spec:
      containers:
        - name: image-server
          image: image-server:latest
          env:
            - name: database-user
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-user
            - name: database-password
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-password
            - name: database-host
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-host
            - name: database-db
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key:  database-db
            - name: service_point
              valueFrom:
                configMapKeyRef:
                  name: service-point
                  key: url-external
            - name: bucket-base-name
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-base-name
          ports:
            - containerPort: 5000
          resources:
            limits:
                cpu: '2'
                memory: 1G
            requests:
              cpu: 400m
              memory: 100M
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  name: image-server
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: image-server
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: image-server
spec:
  to:
    kind: Service
    name: image-server
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
  wildcardPolicy: None
