---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
stringData:
    AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID_replace_me     
    AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY_replace_me 
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
    database-user: xraylab     
    database-password: xraylab
    database-root-password: xraylab
    database-host: xraylabdb 
    database-db: xraylabdb 