{
 "title": "Smart City - ULEZ London",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "# London\n\n## Ultra Low Emissions Zone"
   }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 } },
  {
   "title": "Wanted vehicles location",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "rawSql": "SELECT e.date AS Event, e.event_vehicle_detected_plate_number AS Plate,\n  CASE WHEN stationa1 = 'true' THEN 'stationa1'\n       WHEN stationa13 = 'true' THEN 'stationa13' \n       WHEN stationa2 = 'true' THEN 'stationa2'\n       WHEN stationa23 = 'true' THEN 'stationa23'\n       WHEN stationb313 = 'true' THEN 'stationb313'\n       WHEN stationa4202 = 'true' THEN 'stationa4202'\n       WHEN stationb504 = 'true' THEN 'stationb504'\n       WHEN stationa41 = 'true' THEN 'stationa41'\n       WHEN stationa5201 = 'true' THEN 'stationa5201'\n       END AS Station\nFROM event AS e\nLEFT JOIN vehicle_metadata AS v\nON e.event_vehicle_detected_plate_number = v.vehicle_registered_plate_number\nWHERE e.event_vehicle_detected_plate_number = 'LCA2555' OR e.event_vehicle_detected_plate_number = 'G526JHD'\nORDER by e.date DESC \nLIMIT 3\n"
    }
   ]
  },
  {
   "title": "Vehicles per station over period",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A23\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa23 = 'true'\nGROUP BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A1\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa1 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A4202\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa4202 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A41\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa41 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station B504\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationb504 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A5201\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa5201 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A13\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa13 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station B313\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationb313 = 'true'\nGROUP BY 1\n"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  count(event_id) as \"Station A2\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa2 = 'true'\nGROUP BY 1\n"
    }
   ]
  },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa23 = 'true'\n"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa2 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationb313 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationb504 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa4202 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa1 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa13 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa5201 = 'true'"
    },
    {
     "rawSql": "SELECT\n  count(event_id) as \"value\",\n  max(date) as \"time\"\nFROM event\nWHERE\n  $__timeFilter(date) AND stationa41 = 'true'"
    }
   ]
  },
  {
   "title": "Last detected car",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Last detected car",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT e.event_vehicle_detected_plate_number AS \"Detected plate\"\n                    FROM event  AS e\n                    LEFT JOIN vehicle_metadata AS v\n                    ON e.event_vehicle_detected_plate_number = v.vehicle_registered_plate_number\n                    ORDER by e.date DESC\n                    LIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT              v.vehicle_make_model AS \"Model\"\n                    FROM event  AS e\n                    LEFT JOIN vehicle_metadata AS v\n                    ON e.event_vehicle_detected_plate_number = v.vehicle_registered_plate_number\n                    ORDER by e.date DESC\n                    LIMIT 1"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT              v.vehicle_owner_name AS \"Owner\"\n                    FROM event  AS e\n                    LEFT JOIN vehicle_metadata AS v\n                    ON e.event_vehicle_detected_plate_number = v.vehicle_registered_plate_number\n                    ORDER by e.date DESC\n                    LIMIT 1"
    }
   ]
  }
 ]
}