== Kafka Edge to Core deployment instructions

=== Requirements

- Red Hat OpenShift Container Platform
- Red Hat AMQ Streams
- Red Hat AMQ Streams Edge (Source) Kafka cluster
- Red Hat AMQ Streams Core (Target) Kafka cluster

==== Step 1: Verification

* Make sure Edge and Core Kafka Clusters are setup correctly.

[source,bash]
----
oc get kafka
----

* Identify the Kafka topic that needs to be whitelisted for replication to the Core

[source,bash]
----
oc get kafkatopics
----
==== Step 2: Setup Mirror Maker

* To setup mirror maker edit `mirror-maker.yaml` with the folowing parameters as per your enviroment.

- Source kafka bootStrap server endpoint
- Target kafka bootstrap server endpoints
- Topic Name under `topicsPattern`

[source,bash]
----
oc create -f mirror-maker.yaml;
----

* Verify Kafka Mirror Maker instances

[source,bash]
----
oc get kafkamirrormaker2
----

At this point Kafka Mirror Maker has been configured to asynchronously replicate messages from source kafka cluster to target kafka cluster. Thus providing you an architectural choice to connect various edge locations to a single core cluster with seamless data transfer.
