---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: risk-assessment
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/rh-data-services/xraylab-risk-assessment:v2.0"
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-generator
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/rh-data-services/xraylab-image-generator:v2.0"
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-server
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/rh-data-services/xraylab-image-server:v2.0"
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: image-init
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: "quay.io/rh-data-services/xraylab-image-init:v2.0"
      importPolicy: {}
      referencePolicy:
        type: Source
