apiVersion: batch/v1
kind: Job
metadata:
  name: xray-source
spec:
  selector: {}
  template:
    metadata:
      name: xray-source
    spec:
      containers:
        - name: base-copy
          resources:
            limits:
              cpu: '1'
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 500Mi
          image: quay.io/rh-data-services/xraylab-image-init:v2.0
          imagePullPolicy: Always
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: SERVICE_POINT
              valueFrom:
                configMapKeyRef:
                  name: service-point
                  key: url
            - name: BUCKET_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: buckets-config
                  key: bucket-source
      restartPolicy: Never