apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: smartcity
spec:
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
  config:
    auth.basic:
      enabled: true
    plugins:
      plugin_admin_enabled: true
    security:
      admin_password: secret
      admin_user: admin
  ingress:
    enabled: true
    termination: edge
    tlsEnabled: true
