apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-grafana-datasource
  namespace: smartcity
spec:
  datasources:
    - basicAuthUser: internal
      access: proxy
      editable: true
      isDefault: false
      secureJsonData:
        httpHeaderValue1: 'Bearer BEARER_TOKEN'
      name: prometheus
      url: 'https://prometheus-k8s.openshift-monitoring.svc:9091'
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      type: prometheus
  name: grafana-prometheus-datasource.yaml
