== JumpStart Library patterns

WARNING: Work In Progress

Each pattern that you will find in this folder is documented in the same way:

----
└── pattern/pattern-x
    ├── README.adoc :   Full description of the pattern
    │                   with use cases, reference implementations,
    │                   video tutorial links,...
    ├── deployment/
    │   ├── ... :   Instructions and code to deploy
    │   └── ...     the pattern.
    ├── examples/
    │   ├── ... :   Various basic examples on how to
    │   └── ...     use or implement the pattern.
    └── src/
        ├── ... :   Sources for various elements used in the pattern,
        └── ...     like container images, glue code,...

----

=== List of patterns

* link:patterns/kafka-producer/README.adoc[Kafka Producer]: Produce kafka events from your application code
* link:patterns/kafka-consumer/README.adoc[Kafka Consumer]: Consume Kafka events from your application code
* link:patterns/kafka-edge-to-core/README.adoc[Kafka Edge-to-Core]: Store-and-forward kafka events from edge to core
* link:patterns/kafka-to-serverless/README.adoc[Kafka to Serverless]: Use Kafka as an event source to trigger OpenShift Serverless functions
* link:patterns/bucket-notification/README.adoc[Bucket notification]: Send events to various endpoints when something occurs on your Ceph-based object storage
