== kafka-to-serverless deployment instructions

=== Requirements

- Red Hat OpenShift Container Platform
- Red Hat AMQ Streams : Operator should be instlled and Kafka cluster must be created
- Red Hat OpenShift Serverless : Operator must be installed

=== Part 1: Setting up

Once Red Hat  OpenShift Serverless operator has been installed, we would create `KnativeServing` , `KnativeEventing` and `KnativeKafka` instances

==== Step 1: Create required Knative instances

* Apply the YAML file to create knative instances

[source,bash]
----
oc create -f 01_knative_serving_eventing_kafka_setup.yaml
----
==== Step 2: Verify Knative Instances

[source,bash]
----
oc get po -n knative-serving
oc get po -n knative-eventing
----
* Pod with prefix `kafka-controller-manager` represents Knative Kafka Event Source

=== Part 2: Knative Serving

Knative Serving is your serverless business logic that you would like to execute based on the event generated by Kafka.

For example purpose we are using a greeter service, in your use case you might want to replaced that with your own business logic.

==== Step 1: Create Knative Serving

* Apply the YAML file to create knative serving

[source,bash]
----
oc create -f 02_knative_service.yaml
----

==== Step 2: Verify Knative Serving

[source,bash]
----
oc get serving
----

=== Part 3: Knative Eventing

Knative Eventing  enables developers to use an event-driven architecture with serverless applications. An event-driven architecture is based on the concept of decoupled relationships between event producers that create events, and event sinks, or consumers, that receive them.

==== Step 1: Create Knative Eventing

* To create a Knative Eventing, we need to create a Kafka Event Source. Before you apply the following YAML file, please make sure to edit `topics` and `bootstrapServers` to match your Kafka cluster. Also make sure to use the correct Knative Service (serving) that you have created in the previous step.

[source,bash]
----
oc create -f 03_knative_kafka_source.yaml
----

==== Step 2: Verify Knative Eventing

[source,bash]
----
oc get kafkasource
----

At this point, as soon as new messages are received in Kafka topic `lpr`, Knative Eventing will trriger the Knative Service `greeter` to execute the business logic, allowing you to have event-driven serverless application running on OpenShift Container Platform.
