== Kafka to Object Storage (using Secor) deployment instructions

=== Requirements

- Red Hat OpenShift Container Platform
- Red Hat AMQ Streams
- Red Hat OpenShift Data Foundation : Object Bucket Claim Storage class with name `ocs-storagecluster-ceph-rgw`

=== Part 1: Object Bucket Claim

An Object Bucket Claim can be used to request an S3 compatible bucket backend for your workloads. Similar to Persistent Volumes, you can add the details of the Object Bucket claim to your application’s YAML, and get the object service endpoint, access key, and secret access key available in a configuration map and secret

==== Step 1: Create OpenShift Data Foundation Object Bucket claim

[source,bash]
----
oc create -f kafka-to-object-storage/deployment/1_obc_secor.yaml
----

=== Part 2: Zookeeper Entrance

When Strimzi deploys the Kafka cluster, it keeps the ZooKeeper secure and inaccessible from any other application. Zookeeper Entrance deploys an Stunnel proxy which exposes the Zookeeper without any authentication and encryption, however uses Cluster Operator certificate to authenticate against Zookeeper and handle encryption.

Secor uses the Zookeeper Entrance to connect to the Zookeeper instance of Kafka Cluser and fetch the offsets.

==== Step 2: Deploy Zookeeper Entrance

[source,bash]
----
oc create -f kafka-to-object-storage/deployment/2_zookeeper_entrance.yaml
----

=== Part 3: Deployment Config
Secor is a service persisting Kafka logs to Object Storage Systems. The following deployment config is used to deploy the Secor service.

==== Step 1: Create DeploymentConfig

[source,bash]
----
oc create -f patterns/kafka-consumer/deployment/3_deployment_config.yaml
----
